/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINMAX_H_RPCGEN
#define _MINMAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct THREE_NUMBERS {
	int a;
	int b;
	int c;
};
typedef struct THREE_NUMBERS THREE_NUMBERS;

struct MIN_MAX {
	int state;
	int min;
	int max;
};
typedef struct MIN_MAX MIN_MAX;

struct REQUEST {
	int handle;
};
typedef struct REQUEST REQUEST;

#define MINMAX 0x0ABECEDA
#define MINMAX_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define calc_min_max 1
extern  REQUEST * calc_min_max_1(THREE_NUMBERS *, CLIENT *);
extern  REQUEST * calc_min_max_1_svc(THREE_NUMBERS *, struct svc_req *);
#define get_min_max_result 2
extern  MIN_MAX * get_min_max_result_1(REQUEST *, CLIENT *);
extern  MIN_MAX * get_min_max_result_1_svc(REQUEST *, struct svc_req *);
extern int minmax_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calc_min_max 1
extern  REQUEST * calc_min_max_1();
extern  REQUEST * calc_min_max_1_svc();
#define get_min_max_result 2
extern  MIN_MAX * get_min_max_result_1();
extern  MIN_MAX * get_min_max_result_1_svc();
extern int minmax_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_THREE_NUMBERS (XDR *, THREE_NUMBERS*);
extern  bool_t xdr_MIN_MAX (XDR *, MIN_MAX*);
extern  bool_t xdr_REQUEST (XDR *, REQUEST*);

#else /* K&R C */
extern bool_t xdr_THREE_NUMBERS ();
extern bool_t xdr_MIN_MAX ();
extern bool_t xdr_REQUEST ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINMAX_H_RPCGEN */
